/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Classes */
        get: operations["classes_api_assets_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_assets_get"];
        put?: never;
        /** Add Asset */
        post: operations["add_asset_api_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_assets_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Asset Detail */
        get: operations["asset_detail_api_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/quote/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quote */
        get: operations["quote_api_market_quote__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quotes
         * @description Quotes for several assets at once. An asset without a quote maps to null.
         */
        get: operations["quotes_api_market_quotes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/status/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market Status */
        get: operations["market_status_api_market_status__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/history/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description Bars in ascending time order. A range with no bars returns an empty list.
         */
        get: operations["history_api_market_history__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Portfolios */
        get: operations["list_portfolios_api_portfolios_get"];
        put?: never;
        /** Create Portfolio */
        post: operations["create_portfolio_api_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Detail */
        get: operations["portfolio_detail_api_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Portfolio
         * @description Deletes the portfolio with its positions, orders, trades and history.
         */
        delete: operations["delete_portfolio_api_portfolios__portfolio_id__delete"];
        options?: never;
        head?: never;
        /** Rename Portfolio */
        patch: operations["rename_portfolio_api_portfolios__portfolio_id__patch"];
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Track Asset */
        post: operations["track_asset_api_portfolios__portfolio_id__assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Untrack Asset */
        delete: operations["untrack_asset_api_portfolios__portfolio_id__assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Value History */
        get: operations["value_history_api_portfolios__portfolio_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fee-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fee Profiles */
        get: operations["fee_profiles_api_fee_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/fee-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio Fee Profiles */
        get: operations["portfolio_fee_profiles_api_portfolios__portfolio_id__fee_profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/fee-profiles/{asset_class}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Choose Fee Profile */
        put: operations["choose_fee_profile_api_portfolios__portfolio_id__fee_profiles__asset_class__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/orders/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Order
         * @description Estimated price, fee and cash effect, computed with the rules an actual fill uses.
         */
        post: operations["preview_order_api_portfolios__portfolio_id__orders_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_portfolios__portfolio_id__orders_get"];
        put?: never;
        /** Place Order */
        post: operations["place_order_api_portfolios__portfolio_id__orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Order */
        post: operations["cancel_order_api_portfolios__portfolio_id__orders__order_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trades */
        get: operations["list_trades_api_portfolios__portfolio_id__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/trades.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trades Csv */
        get: operations["trades_csv_api_portfolios__portfolio_id__trades_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolios/{portfolio_id}/trades/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trade Detail */
        get: operations["trade_detail_api_portfolios__portfolio_id__trades__trade_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddAssetIn */
        AddAssetIn: {
            /** Source */
            source: string;
            /** Symbol */
            symbol: string;
        };
        /** AssetClassOut */
        AssetClassOut: {
            /** Asset Class */
            asset_class: string;
            /** Count */
            count: number;
        };
        /** AssetOut */
        AssetOut: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class: string;
            /** Quote Currency */
            quote_currency: string;
            /** Quantity Step */
            quantity_step: string;
            /** Min Order Size */
            min_order_size: string | null;
            /** Calendar */
            calendar: string;
            /** Available */
            available: boolean;
            /** Source */
            source: string | null;
            /** Seeded */
            seeded: boolean;
            /** Rank */
            rank: number | null;
        };
        /** BarOut */
        BarOut: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Open */
            open: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Close */
            close: string;
            /** Volume */
            volume: string | null;
        };
        /** Credentials */
        Credentials: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ExchangeRateOut */
        ExchangeRateOut: {
            /** Maker */
            maker: string;
            /** Taker */
            taker: string;
            /** Source Url */
            source_url?: string | null;
            /** Note */
            note?: string | null;
        };
        /** FeeProfileOut */
        FeeProfileOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Venue */
            venue: string;
            /** Asset Classes */
            asset_classes: string[];
            /** Default For */
            default_for: string[];
            /** Currency */
            currency: string | null;
            /** Maker Rate */
            maker_rate: string;
            /** Taker Rate */
            taker_rate: string;
            /** Per Unit */
            per_unit: string;
            /** Fixed */
            fixed: string;
            /** Min Fee */
            min_fee: string | null;
            /** Max Fee */
            max_fee: string | null;
            /** Max Fee Rate */
            max_fee_rate: string | null;
            /** Assumed Spread */
            assumed_spread: string;
            /** Exchange Rates */
            exchange_rates: {
                [key: string]: components["schemas"]["ExchangeRateOut"];
            } | null;
            /** Source Url */
            source_url: string | null;
            /** Source Note */
            source_note: string | null;
            /**
             * Checked On
             * Format: date
             */
            checked_on: string;
        };
        /** FeeSelectionIn */
        FeeSelectionIn: {
            /** Profile Key */
            profile_key: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryOut */
        HistoryOut: {
            /** Asset Id */
            asset_id: number;
            /** Resolution */
            resolution: string;
            /** Source */
            source: string | null;
            /** Bars */
            bars: components["schemas"]["BarOut"][];
        };
        /** MarketStatusOut */
        MarketStatusOut: {
            /** Asset Id */
            asset_id: number;
            /** Is Open */
            is_open: boolean;
            /** Next Open */
            next_open: string | null;
        };
        /** OrderIn */
        OrderIn: {
            /** Asset Id */
            asset_id: number;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /**
             * Type
             * @enum {string}
             */
            type: "market" | "limit" | "stop";
            /** Quantity */
            quantity: number | string;
            /** Limit Price */
            limit_price?: number | string | null;
            /** Stop Price */
            stop_price?: number | string | null;
            /** Client Order Id */
            client_order_id: string;
        };
        /** OrderOut */
        OrderOut: {
            /** Id */
            id: number;
            /** Portfolio Id */
            portfolio_id: number;
            /** Asset Id */
            asset_id: number;
            /** Asset Symbol */
            asset_symbol: string;
            /** Client Order Id */
            client_order_id: string;
            /** Side */
            side: string;
            /** Type */
            type: string;
            /** Quantity */
            quantity: string;
            /** Limit Price */
            limit_price: string | null;
            /** Stop Price */
            stop_price: string | null;
            /** Status */
            status: string;
            /** Reserved Cash */
            reserved_cash: string;
            /** Reject Reason */
            reject_reason: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Trade Id */
            trade_id?: number | null;
        };
        /** PortfolioDetail */
        PortfolioDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Base Currency */
            base_currency: string;
            /** Starting Cash */
            starting_cash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Total Value */
            total_value: string;
            /** Total Return */
            total_return: string;
            /** Total Return Pct */
            total_return_pct: string;
            /** Stale */
            stale: boolean;
            /** Cash */
            cash: string;
            /** Reserved Cash */
            reserved_cash: string;
            /** Available Cash */
            available_cash: string;
            /** Realized */
            realized: string;
            /** Unrealized */
            unrealized: string;
            /** Fees Paid */
            fees_paid: string;
            /** Fees By Class */
            fees_by_class: {
                [key: string]: string;
            };
            /** Oldest Quote Age Seconds */
            oldest_quote_age_seconds: number | null;
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Tracked */
            tracked: components["schemas"]["TrackedAssetOut"][];
        };
        /** PortfolioIn */
        PortfolioIn: {
            /** Name */
            name: string;
            /** Base Currency */
            base_currency: string;
            /** Starting Cash */
            starting_cash: number | string;
        };
        /** PortfolioRename */
        PortfolioRename: {
            /** Name */
            name: string;
        };
        /** PortfolioSummary */
        PortfolioSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Base Currency */
            base_currency: string;
            /** Starting Cash */
            starting_cash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Total Value */
            total_value: string;
            /** Total Return */
            total_return: string;
            /** Total Return Pct */
            total_return_pct: string;
            /** Stale */
            stale: boolean;
        };
        /** PositionOut */
        PositionOut: {
            asset: components["schemas"]["AssetOut"];
            /** Quantity */
            quantity: string;
            /** Committed */
            committed: string;
            /** Avg Cost */
            avg_cost: string;
            /** Price */
            price: string | null;
            /** Price Currency */
            price_currency: string;
            /** Price Base */
            price_base: string | null;
            /** Market Value */
            market_value: string;
            /** Unrealized */
            unrealized: string;
            /** Unrealized Pct */
            unrealized_pct: string | null;
            /** Stale */
            stale: boolean;
            /** Unpriced */
            unpriced: boolean;
            /** Quote Source */
            quote_source: string | null;
            /** Quote Observed At */
            quote_observed_at: string | null;
        };
        /** PreviewIn */
        PreviewIn: {
            /** Asset Id */
            asset_id: number;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /**
             * Type
             * @enum {string}
             */
            type: "market" | "limit" | "stop";
            /** Quantity */
            quantity: number | string;
            /** Limit Price */
            limit_price?: number | string | null;
            /** Stop Price */
            stop_price?: number | string | null;
        };
        /** PreviewOut */
        PreviewOut: {
            /** Estimated Price */
            estimated_price: string;
            /** Price Currency */
            price_currency: string;
            /** Fx Rate */
            fx_rate: string;
            /** Liquidity */
            liquidity: string;
            /** Fills Now */
            fills_now: boolean;
            /** Value Base */
            value_base: string;
            /** Fee */
            fee: string;
            /** Cash Change */
            cash_change: string;
            /** Base Currency */
            base_currency: string;
            /** Fee Profile Name */
            fee_profile_name: string;
            /** Fee Rate Fallback */
            fee_rate_fallback: boolean;
            /** Quote Source */
            quote_source: string | null;
            /** Quote Observed At */
            quote_observed_at: string | null;
            /** Available Cash */
            available_cash: string;
        };
        /** QuoteOut */
        QuoteOut: {
            /** Asset Id */
            asset_id: number;
            /** Last */
            last: string;
            /** Bid */
            bid: string | null;
            /** Ask */
            ask: string | null;
            /** Last Price Only */
            last_price_only: boolean;
            /** Currency */
            currency: string;
            /** Source */
            source: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /** Age Seconds */
            age_seconds: number;
            /** Fresh */
            fresh: boolean;
            /** Stale */
            stale: boolean;
            /** Delayed */
            delayed: boolean;
            /** Market Open */
            market_open: boolean;
            /** Next Open */
            next_open: string | null;
        };
        /** SearchResultOut */
        SearchResultOut: {
            /** Source */
            source: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Instrument Type */
            instrument_type: string;
            /** Asset Class */
            asset_class: string | null;
            /** Supported */
            supported: boolean;
            /** Exchange */
            exchange: string | null;
            /** Asset Id */
            asset_id: number | null;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Value */
            value: string;
            /** Kind */
            kind: string;
        };
        /** TrackAssetIn */
        TrackAssetIn: {
            /** Asset Id */
            asset_id: number;
        };
        /** TrackedAssetOut */
        TrackedAssetOut: {
            asset: components["schemas"]["AssetOut"];
            quote: components["schemas"]["QuoteOut"] | null;
            /** Position Quantity */
            position_quantity: string;
        };
        /** TradeOut */
        TradeOut: {
            /** Id */
            id: number;
            /** Order Id */
            order_id: number;
            /** Portfolio Id */
            portfolio_id: number;
            /** Asset Id */
            asset_id: number;
            /** Asset Symbol */
            asset_symbol: string;
            /** Asset Class */
            asset_class: string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /** Side */
            side: string;
            /** Quantity */
            quantity: string;
            /** Price */
            price: string;
            /** Quote Currency */
            quote_currency: string;
            /** Quote Source */
            quote_source: string;
            /**
             * Quote Observed At
             * Format: date-time
             */
            quote_observed_at: string;
            /** Fx Rate */
            fx_rate: string;
            /** Value Base */
            value_base: string;
            /** Liquidity */
            liquidity: string;
            /** Fee */
            fee: string;
            /** Fee Profile Name */
            fee_profile_name: string;
            /** Fee Terms */
            fee_terms: {
                [key: string]: unknown;
            };
            /** Fee Rate Fallback */
            fee_rate_fallback: boolean;
            /** Cash Change */
            cash_change: string;
            /** Realized Pnl */
            realized_pnl: string;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    classes_api_assets_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetClassOut"][];
                };
            };
        };
    };
    list_assets_api_assets_get: {
        parameters: {
            query?: {
                asset_class?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_asset_api_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddAssetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_assets_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_detail_api_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_api_market_quote__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quotes_api_market_quotes_get: {
        parameters: {
            query: {
                /** @description Comma-separated asset ids */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["QuoteOut"] | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    market_status_api_market_status__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_market_history__asset_id__get: {
        parameters: {
            query?: {
                resolution?: "1d" | "1h";
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_portfolios_api_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"][];
                };
            };
        };
    };
    create_portfolio_api_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_detail_api_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_api_portfolios__portfolio_id__delete: {
        parameters: {
            query?: {
                confirm?: boolean;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_portfolio_api_portfolios__portfolio_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_asset_api_portfolios__portfolio_id__assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackAssetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    untrack_asset_api_portfolios__portfolio_id__assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: number;
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    value_history_api_portfolios__portfolio_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fee_profiles_api_fee_profiles_get: {
        parameters: {
            query?: {
                asset_class?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeProfileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_fee_profiles_api_portfolios__portfolio_id__fee_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["FeeProfileOut"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    choose_fee_profile_api_portfolios__portfolio_id__fee_profiles__asset_class__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_class: string;
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeeSelectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_order_api_portfolios__portfolio_id__orders_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_portfolios__portfolio_id__orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_order_api_portfolios__portfolio_id__orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_portfolios__portfolio_id__orders__order_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trades_api_portfolios__portfolio_id__trades_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trades_csv_api_portfolios__portfolio_id__trades_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trade_detail_api_portfolios__portfolio_id__trades__trade_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: number;
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
