"""fee profiles

Revision ID: 20c7a58fdded
Revises: 92f5eed13d43
Create Date: 2026-09-30 10:50:02.186129

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.dbtypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20c7a58fdded"
down_revision: str | Sequence[str] | None = "92f5eed13d43"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fee_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("venue", sa.String(length=120), nullable=False),
        sa.Column("asset_classes", sa.JSON(), nullable=False),
        sa.Column("default_for", sa.JSON(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("maker_rate", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("taker_rate", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("per_unit", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("fixed", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("min_fee", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("max_fee", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("max_fee_rate", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("assumed_spread", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("exchange_rates", sa.JSON(), nullable=True),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("source_note", sa.String(length=500), nullable=True),
        sa.Column("checked_on", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_profiles")),
        sa.UniqueConstraint("key", name=op.f("uq_fee_profiles_key")),
    )
    op.create_table(
        "portfolio_fee_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("asset_class", sa.String(length=16), nullable=False),
        sa.Column("fee_profile_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fee_profile_id"],
            ["fee_profiles.id"],
            name=op.f("fk_portfolio_fee_profiles_fee_profile_id_fee_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_fee_profiles_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_fee_profiles")),
        sa.UniqueConstraint(
            "portfolio_id", "asset_class", name=op.f("uq_portfolio_fee_profiles_portfolio_id")
        ),
    )
    with op.batch_alter_table("portfolio_fee_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_portfolio_fee_profiles_portfolio_id"), ["portfolio_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("portfolio_fee_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_portfolio_fee_profiles_portfolio_id"))

    op.drop_table("portfolio_fee_profiles")
    op.drop_table("fee_profiles")
    # ### end Alembic commands ###
