"""orders and trades

Revision ID: 2f0c7ef858fa
Revises: 20c7a58fdded
Create Date: 2026-09-30 10:50:18.693932

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.dbtypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f0c7ef858fa"
down_revision: str | Sequence[str] | None = "20c7a58fdded"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("client_order_id", sa.String(length=64), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("type", sa.String(length=8), nullable=False),
        sa.Column("quantity", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("limit_price", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("stop_price", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("reserved_cash", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("reject_reason", sa.String(length=200), nullable=True),
        sa.Column("created_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column("closed_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_orders_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_orders_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("portfolio_id", "client_order_id", name=op.f("uq_orders_portfolio_id")),
    )
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_orders_portfolio_id"), ["portfolio_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_orders_status"), ["status"], unique=False)

    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("executed_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("quantity", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("price", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("quote_currency", sa.String(length=8), nullable=False),
        sa.Column("quote_source", sa.String(length=32), nullable=False),
        sa.Column("quote_observed_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column("fx_rate", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("value_base", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("liquidity", sa.String(length=5), nullable=False),
        sa.Column("fee", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("fee_profile_name", sa.String(length=120), nullable=False),
        sa.Column("fee_terms", sa.JSON(), nullable=False),
        sa.Column("fee_rate_fallback", sa.Boolean(), nullable=False),
        sa.Column("cash_change", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("realized_pnl", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_trades_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_trades_order_id_orders"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_trades_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
        sa.UniqueConstraint("order_id", name=op.f("uq_trades_order_id")),
    )
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_trades_portfolio_id"), ["portfolio_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trades_portfolio_id"))

    op.drop_table("trades")
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_orders_status"))
        batch_op.drop_index(batch_op.f("ix_orders_portfolio_id"))

    op.drop_table("orders")
    # ### end Alembic commands ###
