"""freigabe protokoll erweiterung und auto exit log

Revision ID: 6ee666ffb666
Revises: d18047f63dfd
Create Date: 2026-10-10 16:50:23.172957

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.dbtypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ee666ffb666"
down_revision: str | Sequence[str] | None = "d18047f63dfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auto_exit_log_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=4), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("trigger_signal_id", sa.String(length=64), nullable=False),
        sa.Column("trigger_signal_kind", sa.String(length=50), nullable=False),
        sa.Column("trigger_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column("sent_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("filled_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("instrument", sa.String(length=64), nullable=False),
        sa.Column("exit_size", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("position_before", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("position_after", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("order_direction", sa.String(length=7), nullable=False),
        sa.Column("position_direction_closed", sa.String(length=5), nullable=False),
        sa.Column("price_age_seconds", sa.Integer(), nullable=False),
        sa.Column("price_source_timestamp", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column("size_was_capped", sa.Boolean(), nullable=False),
        sa.Column("size_capped_to", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("is_reversal", sa.Boolean(), nullable=False),
        sa.Column("reversal_counter_proposal_id", sa.Integer(), nullable=True),
        sa.Column("firmwide_lock_state", sa.String(length=30), nullable=False),
        sa.Column("strategy_lock_state", sa.String(length=30), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("escalation_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("escalation_recipients", sa.JSON(), nullable=True),
        sa.Column("escalation_deadline", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("escalation_result", sa.String(length=200), nullable=True),
        sa.Column("correction_of_id", sa.Integer(), nullable=True),
        sa.Column("created_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["correction_of_id"],
            ["auto_exit_log_entries.id"],
            name=op.f("fk_auto_exit_log_entries_correction_of_id_auto_exit_log_entries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reversal_counter_proposal_id"],
            ["proposals.id"],
            name=op.f("fk_auto_exit_log_entries_reversal_counter_proposal_id_proposals"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_auto_exit_log_entries_strategy_id_strategies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auto_exit_log_entries")),
    )
    with op.batch_alter_table("auto_exit_log_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_auto_exit_log_entries_strategy_id"), ["strategy_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_auto_exit_log_entries_trigger_signal_id"),
            ["trigger_signal_id"],
            unique=False,
        )

    with op.batch_alter_table("proposal_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proposal_snapshot", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("correction_of_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_proposal_events_log_category"), ["log_category"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_proposal_events_correction_of_id_proposal_events"),
            "proposal_events",
            ["correction_of_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("stage2_limit_utilization", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.drop_column("stage2_limit_utilization")

    with op.batch_alter_table("proposal_events", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_proposal_events_correction_of_id_proposal_events"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_proposal_events_log_category"))
        batch_op.drop_column("correction_of_id")
        batch_op.drop_column("proposal_snapshot")

    with op.batch_alter_table("auto_exit_log_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auto_exit_log_entries_trigger_signal_id"))
        batch_op.drop_index(batch_op.f("ix_auto_exit_log_entries_strategy_id"))

    op.drop_table("auto_exit_log_entries")
    # ### end Alembic commands ###
