"""portfolios

Revision ID: 92f5eed13d43
Revises: e8980713abff
Create Date: 2026-09-30 10:49:48.252197

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.dbtypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "92f5eed13d43"
down_revision: str | Sequence[str] | None = "e8980713abff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_currency", sa.String(length=8), nullable=False),
        sa.Column("starting_cash", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("cash", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("realized_pnl", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("fees_paid", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("created_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_portfolios_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolios")),
        sa.UniqueConstraint("user_id", "name", name=op.f("uq_portfolios_user_id")),
    )
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_portfolios_user_id"), ["user_id"], unique=False)

    op.create_table(
        "portfolio_assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("added_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_portfolio_assets_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_portfolio_assets_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_assets")),
        sa.UniqueConstraint(
            "portfolio_id", "asset_id", name=op.f("uq_portfolio_assets_portfolio_id")
        ),
    )
    with op.batch_alter_table("portfolio_assets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_portfolio_assets_portfolio_id"), ["portfolio_id"], unique=False
        )

    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("quantity", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("avg_cost", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"], ["assets.id"], name=op.f("fk_positions_asset_id_assets")
        ),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_positions_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
        sa.UniqueConstraint("portfolio_id", "asset_id", name=op.f("uq_positions_portfolio_id")),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_positions_portfolio_id"), ["portfolio_id"], unique=False
        )

    op.create_table(
        "value_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column("value", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolios.id"],
            name=op.f("fk_value_snapshots_portfolio_id_portfolios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_value_snapshots")),
    )
    with op.batch_alter_table("value_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_value_snapshots_portfolio_id"), ["portfolio_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("value_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_value_snapshots_portfolio_id"))

    op.drop_table("value_snapshots")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_positions_portfolio_id"))

    op.drop_table("positions")
    with op.batch_alter_table("portfolio_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_portfolio_assets_portfolio_id"))

    op.drop_table("portfolio_assets")
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_portfolios_user_id"))

    op.drop_table("portfolios")
    # ### end Alembic commands ###
