"""proposals and strategies

Revision ID: d18047f63dfd
Revises: 2f0c7ef858fa
Create Date: 2026-10-10 15:36:35.835494

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.dbtypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d18047f63dfd"
down_revision: str | Sequence[str] | None = "2f0c7ef858fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gate_status", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
    )
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_strategies_gate_status"), ["gate_status"], unique=False
        )

    op.create_table(
        "proposals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=4), nullable=False),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("strategy_gate_status", sa.String(length=2), nullable=False),
        sa.Column("signal_id", sa.String(length=64), nullable=False),
        sa.Column("parent_proposal_id", sa.Integer(), nullable=True),
        sa.Column("change_generation", sa.Integer(), nullable=False),
        sa.Column("instrument", sa.String(length=64), nullable=False),
        sa.Column("direction", sa.String(length=5), nullable=False),
        sa.Column("size", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("proposal_price", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("stop_price", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("stop_distance", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("stop_distance_pct", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("proposal_kind", sa.String(length=10), nullable=False),
        sa.Column("nav", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("drawdown", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column(
            "aggregate_risk_utilization_before",
            app.dbtypes.Money(precision=38, scale=18),
            nullable=True,
        ),
        sa.Column(
            "aggregate_risk_utilization_after",
            app.dbtypes.Money(precision=38, scale=18),
            nullable=True,
        ),
        sa.Column("risk_eur", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column(
            "correlation_to_open_positions",
            app.dbtypes.Money(precision=38, scale=18),
            nullable=True,
        ),
        sa.Column("price_age_seconds", sa.Integer(), nullable=True),
        sa.Column("limit_utilization", sa.JSON(), nullable=True),
        sa.Column("stage1_result", sa.String(length=10), nullable=True),
        sa.Column("stage1_reason", sa.String(length=500), nullable=True),
        sa.Column("signal_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column("stage1_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("displayed_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("expires_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("decided_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("stage2_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("sent_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("filled_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("decided_by", sa.String(length=100), nullable=True),
        sa.Column("board_action", sa.String(length=10), nullable=True),
        sa.Column("log_category", sa.String(length=30), nullable=True),
        sa.Column("rejection_reason_code", sa.String(length=50), nullable=True),
        sa.Column("rejection_reason_text", sa.String(length=500), nullable=True),
        sa.Column("approval_token", sa.String(length=64), nullable=True),
        sa.Column("limit_price", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("created_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_proposal_id"],
            ["proposals.id"],
            name=op.f("fk_proposals_parent_proposal_id_proposals"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategies.id"], name=op.f("fk_proposals_strategy_id_strategies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposals")),
        sa.UniqueConstraint("approval_token", name=op.f("uq_proposals_approval_token")),
    )
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_proposals_signal_id"), ["signal_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_proposals_state"), ["state"], unique=False)
        batch_op.create_index(batch_op.f("ix_proposals_strategy_id"), ["strategy_id"], unique=False)

    op.create_table(
        "proposal_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("from_state", sa.String(length=30), nullable=True),
        sa.Column("to_state", sa.String(length=30), nullable=False),
        sa.Column("occurred_at", app.dbtypes.UtcDateTime(timezone=True), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("log_category", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
            name=op.f("fk_proposal_events_proposal_id_proposals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal_events")),
    )
    with op.batch_alter_table("proposal_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_proposal_events_proposal_id"), ["proposal_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("proposal_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposal_events_proposal_id"))

    op.drop_table("proposal_events")
    with op.batch_alter_table("proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_proposals_strategy_id"))
        batch_op.drop_index(batch_op.f("ix_proposals_state"))
        batch_op.drop_index(batch_op.f("ix_proposals_signal_id"))

    op.drop_table("proposals")
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategies_gate_status"))

    op.drop_table("strategies")
    # ### end Alembic commands ###
