"""asset catalog

Revision ID: e8980713abff
Revises: 86a93b505e06
Create Date: 2026-09-30 10:49:35.432676

"""

from collections.abc import Sequence

import sqlalchemy as sa

import app.dbtypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8980713abff"
down_revision: str | Sequence[str] | None = "86a93b505e06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("asset_class", sa.String(length=16), nullable=False),
        sa.Column("quote_currency", sa.String(length=8), nullable=False),
        sa.Column("quantity_step", app.dbtypes.Money(precision=38, scale=18), nullable=False),
        sa.Column("min_order_size", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("calendar", sa.String(length=64), nullable=False),
        sa.Column("seeded", sa.Boolean(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("resolved_source", sa.String(length=32), nullable=True),
        sa.Column("resolved_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.Column("last_price", app.dbtypes.Money(precision=38, scale=18), nullable=True),
        sa.Column("last_price_at", app.dbtypes.UtcDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("symbol", name=op.f("uq_assets_symbol")),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assets_asset_class"), ["asset_class"], unique=False)

    op.create_table(
        "asset_source_symbols",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_asset_source_symbols_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_source_symbols")),
        sa.UniqueConstraint("asset_id", "source", name=op.f("uq_asset_source_symbols_asset_id")),
    )
    with op.batch_alter_table("asset_source_symbols", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_asset_source_symbols_asset_id"), ["asset_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("asset_source_symbols", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_source_symbols_asset_id"))

    op.drop_table("asset_source_symbols")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_asset_class"))

    op.drop_table("assets")
    # ### end Alembic commands ###
